/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

const { describe, it, before } = require('node:test')
const assert = require('node:assert')

const Seneca = require('seneca')

const LearnworldsProvider = require('../dist/learnworlds-provider')
const LearnworldsProviderDoc = require('../dist/LearnworldsProvider-doc')

const SenecaMsgTest = require('seneca-msg-test')
const { Maintain } = require('@seneca/maintain')

const { SEED } = require('./seed')

const BasicMessages = require('../dist-test/basic.messages')


describe('learnworlds-provider', () => {

  it('happy', async () => {
    assert.notEqual(LearnworldsProvider, undefined)
    assert.notEqual(LearnworldsProviderDoc, undefined)

    const seneca = await makeSeneca()

    assert.partialDeepStrictEqual(
      await seneca.post('sys:provider,provider:learnworlds,get:info'),
      {
        ok: true,
        name: 'learnworlds',
      },
    )
  })


  it('messages', async () => {
    const seneca = await makeSeneca()
    await SenecaMsgTest(seneca, BasicMessages)()
  })


  it('sdk-export', async () => {
    const seneca = await makeSeneca()
    const sdk = seneca.export('LearnworldsProvider/sdk')()

    assert.equal(typeof sdk.Affiliate, 'function')
    assert.equal(typeof sdk.Assessment, 'function')
    assert.equal(typeof sdk.Bundle, 'function')
    assert.equal(typeof sdk.Calendar, 'function')
    assert.equal(typeof sdk.Certificate, 'function')
    assert.equal(typeof sdk.Community, 'function')
    assert.equal(typeof sdk.CommunityPost, 'function')
    assert.equal(typeof sdk.CommunitySpace, 'function')
    assert.equal(typeof sdk.Coupon, 'function')
    assert.equal(typeof sdk.CouponUsage, 'function')
    assert.equal(typeof sdk.Course, 'function')
    assert.equal(typeof sdk.CourseAnalytics, 'function')
    assert.equal(typeof sdk.CourseContent, 'function')
    assert.equal(typeof sdk.EventLog, 'function')
    assert.equal(typeof sdk.Installment, 'function')
    assert.equal(typeof sdk.Lead, 'function')
    assert.equal(typeof sdk.MultipleSeat, 'function')
    assert.equal(typeof sdk.Payment, 'function')
    assert.equal(typeof sdk.Promotion, 'function')
    assert.equal(typeof sdk.Reporting, 'function')
    assert.equal(typeof sdk.Seat, 'function')
    assert.equal(typeof sdk.SubscriptionPlan, 'function')
    assert.equal(typeof sdk.UnitAnalytics, 'function')
    assert.equal(typeof sdk.UpdateUserProgress, 'function')
    assert.equal(typeof sdk.User, 'function')
    assert.equal(typeof sdk.UserGroup, 'function')
    assert.equal(typeof sdk.UserProgress, 'function')
    assert.equal(typeof sdk.UserRole, 'function')
    assert.equal(typeof sdk.UserSubscription, 'function')
  })


  it('affiliate-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/affiliate').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/affiliate',
    )
  })


  it('bundle-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/bundle').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/bundle',
    )
  })


  it('bundle-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/bundle')
      .load$('bundle0')

    assert.equal(found.id, 'bundle0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/bundle',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('bundle-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/bundle')
      .load$('bundle-nosuch')

    assert.equal(missing, null)
  })


  it('calendar-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/calendar').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/calendar',
    )
  })


  it('certificate-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/certificate').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/certificate',
    )
  })


  it('community_post-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/community_post')
      .load$('community_post0')

    assert.equal(found.id, 'community_post0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/community_post',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('community_post-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/community_post')
      .load$('community_post-nosuch')

    assert.equal(missing, null)
  })


  it('community_space-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/community_space')
      .load$('community_space0')

    assert.equal(found.id, 'community_space0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/community_space',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('community_space-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/community_space')
      .load$('community_space-nosuch')

    assert.equal(missing, null)
  })


  it('course-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/course').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/course',
    )
  })


  it('course-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/course')
      .load$('course0')

    assert.equal(found.id, 'course0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/course',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('course-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/course')
      .load$('course-nosuch')

    assert.equal(missing, null)
  })


  it('course_analytics-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/course_analytics')
      .load$('course_analytics0')

    assert.equal(found.id, 'course_analytics0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/course_analytics',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('course_analytics-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/course_analytics')
      .load$('course_analytics-nosuch')

    assert.equal(missing, null)
  })


  it('course_content-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/course_content').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/course_content',
    )
  })


  it('event_log-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/event_log').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/event_log',
    )
  })


  it('installment-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/installment').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/installment',
    )
  })


  it('lead-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/lead').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/lead',
    )
  })


  it('payment-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/payment').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/payment',
    )
  })


  it('payment-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/payment')
      .load$('payment0')

    assert.equal(found.id, 'payment0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/payment',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('payment-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/payment')
      .load$('payment-nosuch')

    assert.equal(missing, null)
  })


  it('promotion-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/promotion').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/promotion',
    )
  })


  it('promotion-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/promotion')
      .load$('promotion0')

    assert.equal(found.id, 'promotion0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/promotion',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('promotion-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/promotion')
      .load$('promotion-nosuch')

    assert.equal(missing, null)
  })


  it('seat-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/seat')
      .load$('seat0')

    assert.equal(found.id, 'seat0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/seat',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('seat-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/seat')
      .load$('seat-nosuch')

    assert.equal(missing, null)
  })


  it('subscription_plan-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/subscription_plan').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/subscription_plan',
    )
  })


  it('subscription_plan-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/subscription_plan')
      .load$('subscription_plan0')

    assert.equal(found.id, 'subscription_plan0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/subscription_plan',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('subscription_plan-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/subscription_plan')
      .load$('subscription_plan-nosuch')

    assert.equal(missing, null)
  })


  it('user_group-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/user_group').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/user_group',
    )
  })


  it('user_group-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/user_group')
      .load$('user_group0')

    assert.equal(found.id, 'user_group0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/user_group',
    )
  })


  // A 404 from a single-item read is an ordinary "not found" answer, not a
  // failure: the provider turns it into null rather than letting the SDK
  // throw.
  it('user_group-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/user_group')
      .load$('user_group-nosuch')

    assert.equal(missing, null)
  })


  it('user_role-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/user_role').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/user_role',
    )
  })


  it('user_subscription-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca.entity('provider/learnworlds/user_subscription').list$()

    assert.equal(list.length, 2)

    // Entities must come back as Seneca entities under this plugin's canon.
    // The SDK tags its own results with its entity marker, which must not
    // survive into the Seneca entity.
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/user_subscription',
    )
  })


  it('assessment-needs-form_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/assessment').list$({}),
      /form_id is required/,
    )
  })


  it('assessment-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/assessment')
      .list$({ form_id: 'form0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/assessment',
    )
    assert.equal(list[0].form_id, 'form0')
  })


  it('community-needs-space_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/community').list$({}),
      /space_id is required/,
    )
  })


  it('community-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/community')
      .list$({ space_id: 'space0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/community',
    )
    assert.equal(list[0].space_id, 'space0')
  })


  it('coupon_usage-needs-promotion_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/coupon_usage').list$({}),
      /promotion_id is required/,
    )
  })


  it('coupon_usage-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/coupon_usage')
      .list$({ promotion_id: 'promotion0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/coupon_usage',
    )
    assert.equal(list[0].promotion_id, 'promotion0')
  })


  it('multiple_seat-needs-seat_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/multiple_seat').remove$({ id: 'multiple_seat0' }),
      /seat_id is required/,
    )
  })


  it('multiple_seat-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/multiple_seat')
      .list$({ seat_id: 'seat0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/multiple_seat',
    )
    assert.equal(list[0].seat_id, 'seat0')
  })


  it('reporting-needs-user_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/reporting').list$({}),
      /user_id is required/,
    )
  })


  it('reporting-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/reporting')
      .list$({ user_id: 'user0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/reporting',
    )
    assert.equal(list[0].user_id, 'user0')
  })


  it('unit_analytics-needs-course_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/unit_analytics').load$({ id: 'unit_analytics0' }),
      /course_id is required/,
    )
  })


  it('unit_analytics-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/unit_analytics')
      .load$({ course_id: 'course0', id: 'unit_analytics0' })

    assert.equal(found.id, 'unit_analytics0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/unit_analytics',
    )
  })


  it('unit_analytics-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/unit_analytics')
      .load$({ course_id: 'course0', id: 'unit_analytics-nosuch' })

    assert.equal(missing, null)
  })


  it('user-needs-user_group_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user').remove$({ id: 'user0' }),
      /user_group_id is required/,
    )
  })


  it('user-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/user')
      .list$({ user_group_id: 'user_group0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/user',
    )
    assert.equal(list[0].user_group_id, 'user_group0')
  })


  it('user-load', async () => {
    const seneca = await makeSeneca()
    const found = await seneca
      .entity('provider/learnworlds/user')
      .load$({ user_group_id: 'user_group0', id: 'user0' })

    assert.equal(found.id, 'user0')
    assert.equal(
      found.canon$({ string: true }),
      'provider/learnworlds/user',
    )
  })


  it('user-load-missing', async () => {
    const seneca = await makeSeneca()
    const missing = await seneca
      .entity('provider/learnworlds/user')
      .load$({ user_group_id: 'user_group0', id: 'user-nosuch' })

    assert.equal(missing, null)
  })


  it('user_progress-needs-course_id', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_progress').list$({}),
      /course_id is required/,
    )
  })


  it('user_progress-list', async () => {
    const seneca = await makeSeneca()
    const list = await seneca
      .entity('provider/learnworlds/user_progress')
      .list$({ course_id: 'course0', user_id: 'user0' })

    assert.equal(list.length, 2)
    assert.equal(
      list[0].canon$({ string: true }),
      'provider/learnworlds/user_progress',
    )
    assert.equal(list[0].course_id, 'course0')
  })


  it('certificate-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/certificate')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({  }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/learnworlds/certificate',
    )

    const id = made.id

    // This certificate has no load cmd: the API offers no route that reads
    // one back, so the record cannot be re-read here and the remove cannot
    // be confirmed by a follow-up read. The write path is still exercised.
    try {
    }
    finally {
      await ent.remove$({ id: id })
    }
  })


  it('community-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/community')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ space_id: 'space0',  }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/learnworlds/community',
    )

    const id = made.id

    // This community has no load cmd: the API offers no route that reads
    // one back, so the record cannot be re-read here and the remove cannot
    // be confirmed by a follow-up read. The write path is still exercised.
    try {
    }
    finally {
      await ent.remove$({ space_id: 'space0', id: id })
    }
  })


  it('multiple_seat-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/multiple_seat')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ seat_id: 'seat0',  }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/learnworlds/multiple_seat',
    )

    const id = made.id

    // This multiple_seat has no load cmd: the API offers no route that reads
    // one back, so the record cannot be re-read here and the remove cannot
    // be confirmed by a follow-up read. The write path is still exercised.
    try {
    }
    finally {
      await ent.remove$({ seat_id: 'seat0', id: id })
    }
  })


  it('user-crud', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/user')

    // Seneca's convention: an entity WITHOUT an id is a create. The API
    // assigns the id itself, so the saved record comes back with one it chose.
    const made = await ent.make$({ user_group_id: 'user_group0', action: 'crud-action', price: 12345, productId: 'crud-productId', productType: 'crud-productType' }).save$()

    assert.ok(null != made.id)
    assert.equal(
      made.canon$({ string: true }),
      'provider/learnworlds/user',
    )

    const id = made.id

    try {
      const loaded = await ent.load$({ user_group_id: 'user_group0', id: id })
      assert.equal(loaded.id, id)

      // An entity CARRYING an id is an update, not a second create.
      loaded.action = 'crud-action-2'
      const updated = await loaded.save$()

      assert.equal(updated.id, id)
      assert.equal(updated.action, 'crud-action-2')

      const reloaded = await ent.load$({ user_group_id: 'user_group0', id: id })
      assert.equal(reloaded.action, 'crud-action-2')
    }
    finally {
      // Always clean up. The mock and the server both hold data for the
      // process lifetime, so a leaked record changes what later tests see.
      await ent.remove$({ user_group_id: 'user_group0', id: id })
    }

    // remove is real: the record is gone, and reading it is an ordinary
    // not-found rather than an error.
    assert.equal(await ent.load$({ user_group_id: 'user_group0', id: id }), null)
  })


  it('affiliate-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/affiliate')
        .make$({ id: 'affiliate0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('affiliate-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/affiliate')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('assessment-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/assessment')
        .list$({ form_id: 'form0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('bundle-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/bundle')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('calendar-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/calendar')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('certificate-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/certificate')
        .make$({ id: 'certificate0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('certificate-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/certificate')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('community-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/community')
        .make$({ space_id: 'space0', id: 'community0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('community-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/community')
        .list$({ space_id: 'space0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('community_space-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/community_space')
        .make$({ id: 'community_space0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('coupon-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/coupon')
        .make$({ promotion_id: 'promotion0', id: 'coupon0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('coupon_usage-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/coupon_usage')
        .list$({ promotion_id: 'promotion0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('course-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/course')
        .make$({ id: 'course0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('course-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/course')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('course_content-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/course_content')
        .make$({ id: 'course_content0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('course_content-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/course_content')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  // `sections` is an action of `create`: /v2/courses/{id}/sections
  it('course_content-action-sections', async () => {
    const seneca = await makeSeneca()
    let err = null

    try {
      await seneca.entity('provider/learnworlds/course_content')
        .make$({ id: 'course_content0' })
        .directive$({ action$: 'sections' })
        .save$()
    }
    catch (e) { err = e }

    if (null != err) {
      assert.ok(!/is not an action/.test(err.message),
        'the action was refused instead of routed: ' + err.message)
    }
  })


  it('event_log-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/event_log')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('installment-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/installment')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('lead-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/lead')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('multiple_seat-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/multiple_seat')
        .make$({ seat_id: 'seat0', id: 'multiple_seat0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('multiple_seat-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/multiple_seat')
        .list$({ seat_id: 'seat0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('payment-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/payment')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('promotion-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/promotion')
        .make$({ id: 'promotion0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('promotion-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/promotion')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('reporting-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/reporting')
        .list$({ user_id: 'user0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('seat-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/seat')
        .make$({ id: 'seat0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('subscription_plan-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/subscription_plan')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('update_user_progress-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/update_user_progress')
        .make$({ course_id: 'course0', user_id: 'user0', id: 'update_user_progress0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('user-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user')
        .make$({ user_group_id: 'user_group0', id: 'user0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('user-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user')
        .list$({ user_group_id: 'user_group0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  // No action$ named, so this is the plain update — the action route must
  // not run on a call that did not ask for it.
  it('user-save-without-action', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/user')

    const loaded = await ent.load$({ user_group_id: 'user_group0', id: 'user0' })
    loaded.action = 'plain-action'
    const saved = await loaded.save$()

    assert.equal(saved.action, 'plain-action')
    assert.equal(
      saved.canon$({ string: true }),
      'provider/learnworlds/user',
    )
  })


  // `enrollment` is an action of `create`: /v2/users/{id}/enrollment
  it('user-action-enrollment', async () => {
    const seneca = await makeSeneca()
    let err = null

    try {
      await seneca.entity('provider/learnworlds/user')
        .make$({ user_group_id: 'user_group0', id: 'user0' })
        .directive$({ action$: 'enrollment' })
        .save$()
    }
    catch (e) { err = e }

    if (null != err) {
      assert.ok(!/is not an action/.test(err.message),
        'the action was refused instead of routed: ' + err.message)
    }
  })


  it('user_group-action-unknown-save', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_group')
        .make$({ id: 'user_group0' })
        .directive$({ action$: 'no_such_action' })
        .save$(),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('user_group-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_group')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  // No action$ named, so this is the plain update — the action route must
  // not run on a call that did not ask for it.
  it('user_group-save-without-action', async () => {
    const seneca = await makeSeneca()
    const ent = seneca.entity('provider/learnworlds/user_group')

    const loaded = await ent.load$({ id: 'user_group0' })
    loaded.role_id = 'plain-role_id'
    const saved = await loaded.save$()

    assert.equal(saved.role_id, 'plain-role_id')
    assert.equal(
      saved.canon$({ string: true }),
      'provider/learnworlds/user_group',
    )
  })


  // `user-role` is an action of `update`: /v2/users/{id}/user-role
  it('user_group-action-user-role', async () => {
    const seneca = await makeSeneca()
    let err = null

    try {
      await seneca.entity('provider/learnworlds/user_group')
        .make$({ id: 'user_group0' })
        .directive$({ action$: 'user-role' })
        .save$()
    }
    catch (e) { err = e }

    if (null != err) {
      assert.ok(!/is not an action/.test(err.message),
        'the action was refused instead of routed: ' + err.message)
    }
  })


  it('user_progress-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_progress')
        .list$({ course_id: 'course0', user_id: 'user0', action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('user_role-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_role')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('user_subscription-action-unknown-list', async () => {
    const seneca = await makeSeneca()

    await assert.rejects(
      () => seneca.entity('provider/learnworlds/user_subscription')
        .list$({ action$: 'no_such_action' }),
      /action\$ "no_such_action" is not an action/,
    )
  })


  it('maintain', async () => {
    const exclude = []

    // check_default proves the default branch is main by looking for
    // [branch "main"] in .git/config. Only a branch checkout records that
    // section: a pull_request build checks out the merge ref, and the
    // publish build checks out a tag as a detached HEAD. Neither says
    // anything about what the default branch is, so skip rather than fail.
    if ('pull_request' === process.env.GITHUB_EVENT_NAME ||
        'tag' === process.env.GITHUB_REF_TYPE) {
      exclude.push('check_default')
    }

    // url_pkgjson locates package.json by comparing process.cwd() + '/package.json'
    // against a path found with Filehound. On Windows those are the same file
    // spelt with different separators, so the url is never read.
    if ('win32' === process.platform) {
      exclude.push('url_pkgjson')
    }

    await Maintain({ exclude })
  })

})


// Default to the SDK's offline mock transport, seeded from ./seed.
async function makeSeneca(pluginopts) {
  pluginopts = pluginopts || { test: true, testopts: SEED }

  const seneca = Seneca({ legacy: false })
    .test()
    .use('promisify')
    .use('entity')
    .use('env', {
      // Declared so the provider convention is exercised, and defaulted so
      // the suite runs with nothing configured.
      var: {
        $LEARNWORLDS_APIKEY: '',
      },
    })
    .use('provider', {
      provider: {
        learnworlds: {
          keys: {
            apikey: { value: '$LEARNWORLDS_APIKEY' },
          },
        },
      },
    })
    .use(LearnworldsProvider, pluginopts)

  return seneca.ready()
}
