/* Generated by @voxgig/sdkgen. Do not edit. */
'use strict'

// Seed data for the SDK's offline mock transport, so the entity tests
// exercise real code paths without a server.
const SEED = {
  entity: {
    affiliate: {
      affiliate0: {"id":"affiliate0"},
      affiliate1: {"id":"affiliate1"},
    },
    assessment: {
      assessment0: {"form_id":"form0","id":"assessment0"},
      assessment1: {"form_id":"form0","id":"assessment1"},
    },
    bundle: {
      bundle0: {"id":"bundle0"},
      bundle1: {"id":"bundle1"},
    },
    calendar: {
      calendar0: {"id":"calendar0"},
      calendar1: {"id":"calendar1"},
    },
    certificate: {
      certificate0: {"id":"certificate0"},
      certificate1: {"id":"certificate1"},
    },
    community: {
      community0: {"space_id":"space0","id":"community0"},
      community1: {"space_id":"space0","id":"community1"},
    },
    community_post: {
      community_post0: {"id":"community_post0"},
      community_post1: {"id":"community_post1"},
    },
    community_space: {
      community_space0: {"id":"community_space0"},
      community_space1: {"id":"community_space1"},
    },
    coupon: {
      coupon0: {"promotion_id":"promotion0","id":"coupon0"},
      coupon1: {"promotion_id":"promotion0","id":"coupon1"},
    },
    coupon_usage: {
      coupon_usage0: {"promotion_id":"promotion0","id":"coupon_usage0"},
      coupon_usage1: {"promotion_id":"promotion0","id":"coupon_usage1"},
    },
    course: {
      course0: {"titleId":"titleId0","id":"course0"},
      course1: {"titleId":"titleId1","id":"course1"},
    },
    course_analytics: {
      course_analytics0: {"id":"course_analytics0"},
      course_analytics1: {"id":"course_analytics1"},
    },
    course_content: {
      course_content0: {"id":"course_content0"},
      course_content1: {"id":"course_content1"},
    },
    event_log: {
      event_log0: {"id":"event_log0"},
      event_log1: {"id":"event_log1"},
    },
    installment: {
      installment0: {"id":"installment0"},
      installment1: {"id":"installment1"},
    },
    lead: {
      lead0: {"id":"lead0"},
      lead1: {"id":"lead1"},
    },
    multiple_seat: {
      multiple_seat0: {"seat_id":"seat0","uid":"multiple_seat0"},
      multiple_seat1: {"seat_id":"seat0","uid":"multiple_seat1"},
    },
    payment: {
      payment0: {"id":"payment0"},
      payment1: {"id":"payment1"},
    },
    promotion: {
      promotion0: {"id":"promotion0"},
      promotion1: {"id":"promotion1"},
    },
    reporting: {
      reporting0: {"user_id":"user0","id":"reporting0"},
      reporting1: {"user_id":"user0","id":"reporting1"},
    },
    seat: {
      seat0: {"id":"seat0"},
      seat1: {"id":"seat1"},
    },
    subscription_plan: {
      subscription_plan0: {"id":"subscription_plan0"},
      subscription_plan1: {"id":"subscription_plan1"},
    },
    unit_analytics: {
      unit_analytics0: {"course_id":"course0","id":"unit_analytics0"},
      unit_analytics1: {"course_id":"course0","id":"unit_analytics1"},
    },
    update_user_progress: {
      update_user_progress0: {"send_course_complete_email":false,"units":[],"course_id":"course0","user_id":"user0","id":"update_user_progress0"},
      update_user_progress1: {"send_course_complete_email":false,"units":[],"course_id":"course0","user_id":"user0","id":"update_user_progress1"},
    },
    user: {
      user0: {"action":"action0","price":100,"productId":"productId0","productType":"productType0","user_group_id":"user_group0","id":"user0"},
      user1: {"action":"action1","price":200,"productId":"productId1","productType":"productType1","user_group_id":"user_group0","id":"user1"},
    },
    user_group: {
      user_group0: {"role_id":"role_id0","id":"user_group0"},
      user_group1: {"role_id":"role_id1","id":"user_group1"},
    },
    user_progress: {
      user_progress0: {"course_id":"course0","user_id":"user0","id":"user_progress0"},
      user_progress1: {"course_id":"course0","user_id":"user0","id":"user_progress1"},
    },
    user_role: {
      user_role0: {"id":"user_role0"},
      user_role1: {"id":"user_role1"},
    },
    user_subscription: {
      user_subscription0: {"id":"user_subscription0"},
      user_subscription1: {"id":"user_subscription1"},
    },
  },
}

module.exports = { SEED }
