/* Generated by @voxgig/sdkgen. Do not edit. */

const Pkg = require('../package.json')

const { LearnworldsSDK } = require('@voxgig-sdk/learnworlds')

const SdkPkg = require('@voxgig-sdk/learnworlds/package.json')


type LearnworldsProviderOptions = {
  // Options passed straight to the LearnworldsSDK constructor,
  // most usefully `base` to point at a server.
  sdk?: Record<string, any>

  // Run the SDK in offline test mode (in-memory mock transport).
  test?: boolean

  // Test feature options, e.g. {entity: {affiliate: {...}}} to
  // seed the mock with data. Only used when `test` is true.
  testopts?: Record<string, any>
}


function LearnworldsProvider(this: any, options: LearnworldsProviderOptions) {
  const seneca: any = this

  const entityBuilder = this.export('provider/entityBuilder')

  seneca.message('sys:provider,provider:learnworlds,get:info', get_info)

  async function get_info(this: any, _msg: any) {
    return {
      ok: true,
      name: 'learnworlds',
      version: Pkg.version,
      sdk: {
        name: '@voxgig-sdk/learnworlds',
        version: SdkPkg.version,
      },
    }
  }


  // Every SDK operation resolves to an SDK ENTITY rather than raw data (a
  // removed record included: it comes back marked deleted, still holding what
  // it held). Seneca wants plain data, which the entity hands over through
  // data().
  function plain(res: any) {
    return null == res ? res : res.data()
  }


  // Seneca query directives (sort$, limit$, ...) are for the store, not the
  // API, so they must not reach the SDK as match fields.
  function cleanq(q: any) {
    const out: any = {}
    for (const k in (q || {})) {
      if (!k.endsWith('$')) {
        out[k] = q[k]
      }
    }
    return out
  }


  // `action$` — the directive that selects a custom API action instead of
  // the plain cmd. READ BEFORE cleanq strips it, and still stripped from
  // what reaches the SDK as match fields: it is an instruction to the store,
  // like sort$ and limit$, not a value to filter on.
  //
  // THREE PLACES, because seneca-entity puts it in three places depending on
  // how the caller spelled it, and dropping any one of them silently turns a
  // named action into an ordinary call:
  //
  //   list$/load$/remove$({ action$ })         -> msg.q.action$
  //   ent.directive$({ action$ }).save$()      -> msg.action$
  //   const e = ent.make$({...}); e.action$=.. -> msg.ent.action$
  //
  // `make$({ action$ })` is NOT among them and cannot be: seneca-entity's
  // make$ copies only keys without a `$`, plus the four directives it knows
  // (id$, merge$, custom$, directive$), so an unknown trailing-`$` key is
  // dropped before any store sees it. `id$` reads like the precedent for
  // one, but it works only because make$ names it explicitly. The README
  // says so; there is nothing this plugin can check, because nothing arrives.
  function actionOf(msg: any) {
    const q = msg && msg.q
    const ent = msg && msg.ent

    return null != (q && q.action$) ? q.action$ :
      null != (msg && msg.action$) ? msg.action$ :
        null != (ent && ent.action$) ? ent.action$ :
          undefined
  }


  // The SDK argument for an ACTION on a read cmd: everything the caller sent
  // minus Seneca's own directives, with the record key carried across, plus
  // the `$action` selector the SDK dispatches on.
  //
  // WIDER than the canonical argument on purpose. An action route has its own
  // parameters — GitHub's merge takes commit_title and merge_method, which the
  // canonical PATCH knows nothing about — so narrowing to the plain op's
  // required keys would strip the action's whole payload. The SDK still
  // validates: an action whose own point cannot be built is refused with
  // `point_action_invalid` rather than sent somewhere else.
  function actionq(q: any, rk: string, action: string) {
    const out = cleanq(q)

    if ('id' !== rk && null != out.id) {
      out[rk] = out.id
      delete out.id
    }

    out.$action = action
    return out
  }


  // The SDK throws on any non-2xx. A 404 from a single-item read is an
  // ordinary "not found" answer rather than a failure, so return null and let
  // everything else propagate. SDK errors carry the HTTP status at the top
  // level, so ask them rather than digging into `result`.
  async function ornull(action: () => Promise<any>) {
    try {
      return await action()
    }
    catch (e: any) {
      if (true === e?.notFound) {
        return null
      }
      throw e
    }
  }

  // Nested entities cannot build their path without the parent id, so
  // say which key is missing rather than letting the SDK report an opaque
  // 404 on a half-built URL.
  function need_assessment_form_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: assessment ' + cmd + ': form_id is required'
      )
    }
    return value
  }


  function need_community_space_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: community ' + cmd + ': space_id is required'
      )
    }
    return value
  }


  function need_coupon_promotion_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: coupon ' + cmd + ': promotion_id is required'
      )
    }
    return value
  }


  function need_coupon_usage_promotion_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: coupon_usage ' + cmd + ': promotion_id is required'
      )
    }
    return value
  }


  function need_multiple_seat_seat_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: multiple_seat ' + cmd + ': seat_id is required'
      )
    }
    return value
  }


  function need_reporting_user_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: reporting ' + cmd + ': user_id is required'
      )
    }
    return value
  }


  function need_unit_analytics_course_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: unit_analytics ' + cmd + ': course_id is required'
      )
    }
    return value
  }


  function need_update_user_progress_course_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: update_user_progress ' + cmd + ': course_id is required'
      )
    }
    return value
  }


  function need_update_user_progress_user_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: update_user_progress ' + cmd + ': user_id is required'
      )
    }
    return value
  }


  function need_user_user_group_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: user ' + cmd + ': user_group_id is required'
      )
    }
    return value
  }


  function need_user_progress_course_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: user_progress ' + cmd + ': course_id is required'
      )
    }
    return value
  }


  function need_user_progress_user_id(value: any, cmd: string) {
    if (null == value || '' === value) {
      throw new Error(
        '@seneca/learnworlds-provider: user_progress ' + cmd + ': user_id is required'
      )
    }
    return value
  }


  // HOW EACH ENTITY'S id MAPS TO THE API'S OWN KEYS, from the model.
  //
  // `parts`  the path parameters that address one record, in path order.
  //          One part is the ordinary case: the API just calls its key
  //          something other than `id`. Two or more is a compound key,
  //          where no single parameter names the record.
  // `sep`    joins the parts into the one id a Seneca entity carries. A
  //          slash cannot occur inside a path segment, so the join is
  //          unambiguous and the split cannot over-split.
  // `from`   where each part's value lives in a RESPONSE, as a dotted
  //          path. A path parameter's name is not generally a response
  //          field's name: github returns a repo's owner as an OBJECT
  //          (`owner.login`) and its name as `name`, never `repo`.
  //          A part missing here cannot be read back off a response.
  const ID_SPEC: Record<string, { parts: string[], sep: string, from?: Record<string, string> }> = {
    multiple_seat: { parts: ['uid'], sep: '/' },
  }


  // Read a dotted path out of a record. `from` maps a path parameter to
  // wherever the response actually carries it, and that is sometimes inside
  // a nested object.
  function idread(data: any, path: string) {
    let node: any = data
    for (const key of path.split('.')) {
      if (null == node) {
        return undefined
      }
      node = node[key]
    }
    return node
  }


  // The Seneca id, split back into the parameters the API addresses a record
  // with. Refuses a wrong part count rather than sending a URL built from
  // whatever the id happened to contain — that would address a different
  // record, or none, and the 404 would name nothing useful.
  function splitid(name: string, id: any, what: string) {
    const spec = ID_SPEC[name]
    const text = null == id ? '' : String(id)
    const got = 1 === spec.parts.length ? [text] : text.split(spec.sep)

    if (spec.parts.length !== got.length || got.some((p: string) => '' === p)) {
      throw new Error(
        '@seneca/learnworlds-provider: ' + name + ' ' + what +
        ": id must be '" + spec.parts.join(spec.sep) + "', got: " + JSON.stringify(id))
    }

    const out: Record<string, any> = {}
    spec.parts.forEach((p: string, i: number) => { out[p] = got[i] })
    return out
  }


  // The id for a record the API returned.
  //
  // `vals` are the parameters THIS request addressed it with, and they win:
  // a response does not always repeat them. Otherwise the parts are read out
  // of the response through `from`, which is what makes a created or listed
  // record identifiable at all.
  //
  // THE ADDRESSING KEY WINS over an `id` the response already carries. A
  // response often has both — github's pull has a global database `id` and
  // a repo-scoped `number` — and the unrelated one is no use for addressing
  // anything. It is kept as `learnworlds_id` rather than dropped.
  function joinid(name: string, data: any, vals?: any) {
    const spec = ID_SPEC[name]
    if (null == data) {
      return data
    }

    let id = null

    if (null != vals) {
      const got = spec.parts.map((p: string) => vals[p])
      if (got.every((v: any) => null != v && '' !== String(v))) {
        id = got.join(spec.sep)
      }
    }

    if (null == id) {
      const got = spec.parts.map((p: string) =>
        idread(data, (spec.from || {})[p] || p))
      if (got.every((v: any) =>
        null != v && 'object' !== typeof v && '' !== String(v))) {
        id = got.join(spec.sep)
      }
    }

    if (null != id) {
      if (null != data.id && String(data.id) !== id &&
        null == data.learnworlds_id) {
        data.learnworlds_id = data.id
      }
      data.id = id
    }

    return data
  }


  // The custom actions each cmd can reach, as action -> SDK op. An action
  // is an alternative POINT of an ordinary op (`select.$action` in the API
  // model), so `save$` routes by this map rather than assuming update: an
  // action folded into `create` is reached through `save$` too.
  const ACTIONS: Record<string, Record<string, Record<string, string>>> = {
    ["affiliate"]: {
      list: { ["customer"]: 'list', ["lead"]: 'list', ["payment"]: 'list', ["payout_completed"]: 'list', ["payout_due"]: 'list', ["payout_upcoming"]: 'list' },
      save: {},
    },
    ["assessment"]: {
      list: { ["response"]: 'list' },
    },
    ["bundle"]: {
      list: {},
      load: {},
    },
    ["calendar"]: {
      list: {},
    },
    ["certificate"]: {
      list: {},
      save: {},
      remove: {},
    },
    ["community"]: {
      list: { ["collection"]: 'list', ["post"]: 'list', ["space"]: 'list' },
      save: {},
      remove: {},
    },
    ["community_post"]: {
      load: {},
    },
    ["community_space"]: {
      load: {},
      save: {},
    },
    ["coupon"]: {
      save: {},
    },
    ["coupon_usage"]: {
      list: {},
    },
    ["course"]: {
      list: { ["grade"]: 'list', ["user"]: 'list' },
      load: {},
      save: {},
    },
    ["course_analytics"]: {
      load: {},
    },
    ["course_content"]: {
      list: {},
      save: { ["sections"]: 'create' },
    },
    ["event_log"]: {
      list: {},
    },
    ["installment"]: {
      list: { ["active"]: 'list' },
    },
    ["lead"]: {
      list: {},
    },
    ["multiple_seat"]: {
      list: {},
      save: {},
      remove: {},
    },
    ["payment"]: {
      list: {},
      load: { ["invoice_link"]: 'load' },
    },
    ["promotion"]: {
      list: { ["coupon"]: 'list' },
      load: {},
      save: {},
    },
    ["reporting"]: {
      list: {},
    },
    ["seat"]: {
      load: {},
      save: {},
    },
    ["subscription_plan"]: {
      list: {},
      load: {},
    },
    ["unit_analytics"]: {
      load: {},
    },
    ["update_user_progress"]: {
      save: {},
    },
    ["user"]: {
      list: { ["by_product"]: 'list', ["by_segment"]: 'list', ["course"]: 'list', ["product"]: 'list', ["segment"]: 'list' },
      load: { ["seat"]: 'load' },
      save: { ["enrollment"]: 'create', ["suspend"]: 'update', ["tag"]: 'update', ["unsuspend"]: 'update' },
      remove: { ["enrollment"]: 'remove' },
    },
    ["user_group"]: {
      list: {},
      load: {},
      save: { ["user-role"]: 'update' },
    },
    ["user_progress"]: {
      list: {},
    },
    ["user_role"]: {
      list: {},
    },
    ["user_subscription"]: {
      list: {},
    },
  }


  // Resolve an `action$` to the SDK op that serves it, or REFUSE it.
  //
  // Never falls through to the ordinary call. An action name the entity does
  // not have is a caller mistake worth a message that names what is
  // available; performing a plain save instead is the one outcome that must
  // not happen, because it succeeds and does the wrong thing.
  // AN OWN PROPERTY, never an inherited one. `map[name]` resolves
  // `toString`, `constructor`, `valueOf` and the rest off Object's
  // prototype, and each of those is non-null — so the refusal below never
  // fired and the inherited function was handed to the SDK as an op name.
  // That is the silent drop in another hat: the caller named something the
  // entity does not have and was not told. An empty map inherits them all,
  // so a cmd with no actions was the most exposed.
  // THE CMD THAT WOULD WRITE TO THE WRONG RESOURCE.
  //
  // Some entities gather their ops from unrelated routes, and then a cmd's
  // only route addresses something that is not this record: `migration`'s
  // remove deletes a repository's migration ARCHIVE, `user`'s deletes a GPG
  // KEY, `pull`'s deletes a review COMMENT. The id the caller passed is not
  // in the request at all.
  //
  // Such a cmd is refused rather than sent. A caller asking to remove one
  // record must not have a different resource deleted instead, and a
  // successful-looking reply is the worst possible answer. Where the real
  // operation exists it is reachable by name, through `action$`.
  function misaddressed(
    entname: string, cmd: string, key: string, addresses: string[]
  ) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const acts = Object.keys(own.call(ents, cmd) ? ents[cmd] : {}).sort()

    throw new Error(
      '@seneca/learnworlds-provider: ' + entname + ' ' + cmd +
      ': this API has no ' + cmd + ' route for one ' + entname +
      '. Its only ' + cmd + ' route addresses ' + addresses.join(', ') +
      ', not ' + key + ', so the id would be ignored and a different record ' +
      'changed. ' +
      (0 < acts.length ?
        'Name the operation with action$ instead: ' + acts.join(', ') :
        'No action$ of this cmd is available either'))
  }


  function actionop(name: string, entname: string, cmd: string) {
    const own = Object.prototype.hasOwnProperty
    const ents: any = own.call(ACTIONS, entname) ? ACTIONS[entname] : {}
    const map: any = own.call(ents, cmd) ? ents[cmd] : {}
    const op = own.call(map, name) ? map[name] : null

    if (null == op) {
      const valid = Object.keys(map).sort()
      throw new Error(
        '@seneca/learnworlds-provider: ' + entname + ' ' + cmd + ': action$ "' + name +
        '" is not an action of this operation. Valid: ' +
        (0 < valid.length ? valid.join(', ') : '(none)'))
    }

    return op
  }


  const entity: any = {
    affiliate: {
      cmd: {
        list: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    assessment: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    bundle: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
      },
    },

    calendar: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    certificate: {
      cmd: {
        list: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    community: {
      cmd: {
        list: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    community_post: {
      cmd: {
        load: { action: (undefined as any) },
      },
    },

    community_space: {
      cmd: {
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    coupon: {
      cmd: {
        save: { action: (undefined as any) },
      },
    },

    coupon_usage: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    course: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    course_analytics: {
      cmd: {
        load: { action: (undefined as any) },
      },
    },

    course_content: {
      cmd: {
        list: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    event_log: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    installment: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    lead: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    multiple_seat: {
      cmd: {
        list: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    payment: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
      },
    },

    promotion: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    reporting: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    seat: {
      cmd: {
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    subscription_plan: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
      },
    },

    unit_analytics: {
      cmd: {
        load: { action: (undefined as any) },
      },
    },

    update_user_progress: {
      cmd: {
        save: { action: (undefined as any) },
      },
    },

    user: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
        remove: { action: (undefined as any) },
      },
    },

    user_group: {
      cmd: {
        list: { action: (undefined as any) },
        load: { action: (undefined as any) },
        save: { action: (undefined as any) },
      },
    },

    user_progress: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    user_role: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

    user_subscription: {
      cmd: {
        list: { action: (undefined as any) },
      },
    },

  }


  entity.affiliate.cmd.list.action =
    async function list_affiliate(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'affiliate', 'list')
        const found = await this.shared.sdk.Affiliate()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Affiliate().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.affiliate.cmd.save.action =
    async function save_affiliate(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'affiliate', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Affiliate()[op$](data)
        return entize(plain(done))
      }

      const res = await sdk.Affiliate().create(data)

      return entize(plain(res))
    }


  entity.assessment.cmd.list.action =
    async function list_assessment(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'assessment', 'list')
        const found = await this.shared.sdk.Assessment()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_assessment_form_id(q.form_id, 'list')
      const list = await this.shared.sdk.Assessment().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.bundle.cmd.list.action =
    async function list_bundle(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'bundle', 'list')
        const found = await this.shared.sdk.Bundle()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Bundle().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.bundle.cmd.load.action =
    async function load_bundle(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'bundle', 'load')
        const hit = await ornull(() => this.shared.sdk.Bundle()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Bundle().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.calendar.cmd.list.action =
    async function list_calendar(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'calendar', 'list')
        const found = await this.shared.sdk.Calendar()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Calendar().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.certificate.cmd.list.action =
    async function list_certificate(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'certificate', 'list')
        const found = await this.shared.sdk.Certificate()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Certificate().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.certificate.cmd.save.action =
    async function save_certificate(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'certificate', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Certificate()[op$](data)
        return entize(plain(done))
      }

      const res = await sdk.Certificate().update(data)

      return entize(plain(res))
    }


  entity.certificate.cmd.remove.action =
    async function remove_certificate(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'certificate', 'remove')
        const gone = await ornull(() => this.shared.sdk.Certificate()[op$](actionq(msg.q, 'id', action$)))
        return null == gone ? null : entize(plain(gone))
      }

      await ornull(() => this.shared.sdk.Certificate().remove({ id: q.id }))
      return null
    }


  entity.community.cmd.list.action =
    async function list_community(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community', 'list')
        const found = await this.shared.sdk.Community()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_community_space_id(q.space_id, 'list')
      const list = await this.shared.sdk.Community().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.community.cmd.save.action =
    async function save_community(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Community()[op$](data)
        return entize(plain(done))
      }

      need_community_space_id(data.space_id, 'save')
      const res = await sdk.Community().create(data)

      return entize(plain(res))
    }


  entity.community.cmd.remove.action =
    async function remove_community(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community', 'remove')
        const gone = await ornull(() => this.shared.sdk.Community()[op$](actionq(msg.q, 'id', action$)))
        return null == gone ? null : entize(plain(gone))
      }

      await ornull(() => this.shared.sdk.Community().remove({ id: q.id }))
      return null
    }


  entity.community_post.cmd.load.action =
    async function load_community_post(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community_post', 'load')
        const hit = await ornull(() => this.shared.sdk.CommunityPost()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.CommunityPost().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.community_space.cmd.load.action =
    async function load_community_space(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community_space', 'load')
        const hit = await ornull(() => this.shared.sdk.CommunitySpace()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.CommunitySpace().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.community_space.cmd.save.action =
    async function save_community_space(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'community_space', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.CommunitySpace()[op$](data)
        return entize(plain(done))
      }

      const res = null == data.id
        ? await sdk.CommunitySpace().create(data)
        : await sdk.CommunitySpace().update(data)

      return entize(plain(res))
    }


  entity.coupon.cmd.save.action =
    async function save_coupon(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'coupon', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Coupon()[op$](data)
        return entize(plain(done))
      }

      need_coupon_promotion_id(data.promotion_id, 'save')
      const res = await sdk.Coupon().create(data)

      return entize(plain(res))
    }


  entity.coupon_usage.cmd.list.action =
    async function list_coupon_usage(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'coupon_usage', 'list')
        const found = await this.shared.sdk.CouponUsage()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_coupon_usage_promotion_id(q.promotion_id, 'list')
      const list = await this.shared.sdk.CouponUsage().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.course.cmd.list.action =
    async function list_course(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course', 'list')
        const found = await this.shared.sdk.Course()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Course().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.course.cmd.load.action =
    async function load_course(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course', 'load')
        const hit = await ornull(() => this.shared.sdk.Course()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Course().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.course.cmd.save.action =
    async function save_course(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Course()[op$](data)
        return entize(plain(done))
      }

      const res = null == data.id
        ? await sdk.Course().create(data)
        : await sdk.Course().update(data)

      return entize(plain(res))
    }


  entity.course_analytics.cmd.load.action =
    async function load_course_analytics(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course_analytics', 'load')
        const hit = await ornull(() => this.shared.sdk.CourseAnalytics()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.CourseAnalytics().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.course_content.cmd.list.action =
    async function list_course_content(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course_content', 'list')
        const found = await this.shared.sdk.CourseContent()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.CourseContent().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.course_content.cmd.save.action =
    async function save_course_content(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'course_content', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.CourseContent()[op$](data)
        return entize(plain(done))
      }

      const res = await sdk.CourseContent().create(data)

      return entize(plain(res))
    }


  entity.event_log.cmd.list.action =
    async function list_event_log(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'event_log', 'list')
        const found = await this.shared.sdk.EventLog()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.EventLog().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.installment.cmd.list.action =
    async function list_installment(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'installment', 'list')
        const found = await this.shared.sdk.Installment()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Installment().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.lead.cmd.list.action =
    async function list_lead(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'lead', 'list')
        const found = await this.shared.sdk.Lead()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Lead().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.multiple_seat.cmd.list.action =
    async function list_multiple_seat(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'multiple_seat', 'list')
        const found = await this.shared.sdk.MultipleSeat()[op$](actionq(msg.q, 'uid', action$))
        return found.map((data: any) => entize(joinid('multiple_seat', plain(data))))
      }

      const list = await this.shared.sdk.MultipleSeat().list(q)
      return list.map((data: any) => entize(joinid('multiple_seat', plain(data))))
    }


  entity.multiple_seat.cmd.save.action =
    async function save_multiple_seat(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)

      // This API keys a multiple_seat by `uid`; Seneca carries it as `id`.
      if (null == data.uid && null != data.id) {
        data.uid = data.id
      }

      // `learnworlds_id` is this provider's own bookkeeping — the
      // API's unrelated `id`, parked by joinid() so it is not lost. It
      // is not a field of the API's write schema, so it must not travel in
      // the request body: a strict API rejects an unknown property, and a
      // lax one may persist it.
      delete data.learnworlds_id
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'multiple_seat', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.MultipleSeat()[op$](data)
        return entize(joinid('multiple_seat', plain(done)))
      }

      need_multiple_seat_seat_id(data.seat_id, 'save')
      const res = await sdk.MultipleSeat().create(data)

      return entize(joinid('multiple_seat', plain(res)))
    }


  entity.multiple_seat.cmd.remove.action =
    async function remove_multiple_seat(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'multiple_seat', 'remove')
        const gone = await ornull(() => this.shared.sdk.MultipleSeat()[op$](actionq(msg.q, 'uid', action$)))
        return null == gone ? null : entize(joinid('multiple_seat', plain(gone)))
      }

      need_multiple_seat_seat_id(q.seat_id, 'remove')
      await ornull(() => this.shared.sdk.MultipleSeat().remove({ seat_id: q.seat_id, uid: q.id }))
      return null
    }


  entity.payment.cmd.list.action =
    async function list_payment(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'payment', 'list')
        const found = await this.shared.sdk.Payment()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Payment().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.payment.cmd.load.action =
    async function load_payment(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'payment', 'load')
        const hit = await ornull(() => this.shared.sdk.Payment()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Payment().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.promotion.cmd.list.action =
    async function list_promotion(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'promotion', 'list')
        const found = await this.shared.sdk.Promotion()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.Promotion().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.promotion.cmd.load.action =
    async function load_promotion(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'promotion', 'load')
        const hit = await ornull(() => this.shared.sdk.Promotion()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Promotion().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.promotion.cmd.save.action =
    async function save_promotion(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'promotion', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Promotion()[op$](data)
        return entize(plain(done))
      }

      const res = await sdk.Promotion().create(data)

      return entize(plain(res))
    }


  entity.reporting.cmd.list.action =
    async function list_reporting(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'reporting', 'list')
        const found = await this.shared.sdk.Reporting()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_reporting_user_id(q.user_id, 'list')
      const list = await this.shared.sdk.Reporting().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.seat.cmd.load.action =
    async function load_seat(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'seat', 'load')
        const hit = await ornull(() => this.shared.sdk.Seat()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.Seat().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.seat.cmd.save.action =
    async function save_seat(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'seat', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.Seat()[op$](data)
        return entize(plain(done))
      }

      const res = null == data.id
        ? await sdk.Seat().create(data)
        : await sdk.Seat().update(data)

      return entize(plain(res))
    }


  entity.subscription_plan.cmd.list.action =
    async function list_subscription_plan(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'subscription_plan', 'list')
        const found = await this.shared.sdk.SubscriptionPlan()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.SubscriptionPlan().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.subscription_plan.cmd.load.action =
    async function load_subscription_plan(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'subscription_plan', 'load')
        const hit = await ornull(() => this.shared.sdk.SubscriptionPlan()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.SubscriptionPlan().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.unit_analytics.cmd.load.action =
    async function load_unit_analytics(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'unit_analytics', 'load')
        const hit = await ornull(() => this.shared.sdk.UnitAnalytics()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      need_unit_analytics_course_id(q.course_id, 'load')
      const res = await ornull(() => this.shared.sdk.UnitAnalytics().load({ id: q.id, course_id: q.course_id }))
      return null == res ? null : entize(plain(res))
    }


  entity.update_user_progress.cmd.save.action =
    async function save_update_user_progress(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'update_user_progress', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.UpdateUserProgress()[op$](data)
        return entize(plain(done))
      }

      need_update_user_progress_course_id(data.course_id, 'save')
      need_update_user_progress_user_id(data.user_id, 'save')
      const res = await sdk.UpdateUserProgress().create(data)

      return entize(plain(res))
    }


  entity.user.cmd.list.action =
    async function list_user(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user', 'list')
        const found = await this.shared.sdk.User()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.User().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.user.cmd.load.action =
    async function load_user(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user', 'load')
        const hit = await ornull(() => this.shared.sdk.User()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.User().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.user.cmd.save.action =
    async function save_user(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.User()[op$](data)
        return entize(plain(done))
      }

      need_user_user_group_id(data.user_group_id, 'save')
      const res = null == data.id
        ? await sdk.User().create(data)
        : await sdk.User().update(data)

      return entize(plain(res))
    }


  entity.user.cmd.remove.action =
    async function remove_user(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user', 'remove')
        const gone = await ornull(() => this.shared.sdk.User()[op$](actionq(msg.q, 'id', action$)))
        return null == gone ? null : entize(plain(gone))
      }

      need_user_user_group_id(q.user_group_id, 'remove')
      await ornull(() => this.shared.sdk.User().remove({ id: q.id, user_group_id: q.user_group_id }))
      return null
    }


  entity.user_group.cmd.list.action =
    async function list_user_group(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_group', 'list')
        const found = await this.shared.sdk.UserGroup()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.UserGroup().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.user_group.cmd.load.action =
    async function load_user_group(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_group', 'load')
        const hit = await ornull(() => this.shared.sdk.UserGroup()[op$](actionq(msg.q, 'id', action$)))
        return null == hit ? null : entize(plain(hit))
      }

      const res = await ornull(() => this.shared.sdk.UserGroup().load({ id: q.id }))
      return null == res ? null : entize(plain(res))
    }


  entity.user_group.cmd.save.action =
    async function save_user_group(this: any, entize: any, msg: any) {
      const data = msg.ent.data$(false)
      const sdk = this.shared.sdk

      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_group', 'save')
        // The action's OWN payload is the entity's own fields — data$(false)
        // has already dropped every trailing-`$` key, `action$` included,
        // so `$action` is the only thing added here.
        data.$action = action$
        const done = await sdk.UserGroup()[op$](data)
        return entize(plain(done))
      }

      const res = null == data.id
        ? await sdk.UserGroup().create(data)
        : await sdk.UserGroup().update(data)

      return entize(plain(res))
    }


  entity.user_progress.cmd.list.action =
    async function list_user_progress(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_progress', 'list')
        const found = await this.shared.sdk.UserProgress()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      need_user_progress_course_id(q.course_id, 'list')
      need_user_progress_user_id(q.user_id, 'list')
      const list = await this.shared.sdk.UserProgress().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.user_role.cmd.list.action =
    async function list_user_role(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_role', 'list')
        const found = await this.shared.sdk.UserRole()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.UserRole().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entity.user_subscription.cmd.list.action =
    async function list_user_subscription(this: any, entize: any, msg: any) {
      const q = cleanq(msg.q)
      const action$ = actionOf(msg)
      if (null != action$) {
        const op$ = actionop(action$, 'user_subscription', 'list')
        const found = await this.shared.sdk.UserSubscription()[op$](actionq(msg.q, 'id', action$))
        return found.map((data: any) => entize(plain(data)))
      }

      const list = await this.shared.sdk.UserSubscription().list(q)
      return list.map((data: any) => entize(plain(data)))
    }


  entityBuilder(this, {
    provider: {
      name: 'learnworlds',
    },
    entity
  })


  seneca.prepare(async function(this: any) {
    const sdkopts: any = Object.assign({}, options.sdk)

    // This API declares no authentication, so no credential is plumbed. The
    // SDK's auth stage emits nothing for an auth-inactive model and deletes
    // any `authorization` header regardless of options, so a keymap lookup
    // here would read a key that could not reach the wire — which is what the
    // first version of this target did.

    this.shared.sdk = options.test
      ? LearnworldsSDK.test(options.testopts || {}, sdkopts)
      : new LearnworldsSDK(sdkopts)
  })


  return {
    exports: {
      sdk: () => this.shared.sdk,
    },
  }
}


// Default options.
const defaults: LearnworldsProviderOptions = {
  sdk: {},
  test: false,
  testopts: {},
}

Object.assign(LearnworldsProvider, { defaults })

export default LearnworldsProvider

if ('undefined' !== typeof module) {
  module.exports = LearnworldsProvider
}
